
export const POST_FAVORITE = 'POST_FAVORITE';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE'; 


export const POST_CART = 'POST_CART';
export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART'; 
export const DECREASE_CART = 'DECREASE_CART';
export const DELETE_CART_ARRAY= 'DELETE_CART_ARRAY';

export const POST_ORDER = 'POST_ORDER';
export const ADD_ORDER = 'ADD_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';

export const ADD_ADDRESS = 'ADD_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';



export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';


export const SHOPS_LOADING = 'SHOPS_LOADING';
export const ADD_SHOPS = 'ADD_SHOPS';
export const SHOPS_FAILED = 'SHOPS_FAILED';


export const SHOPPRODUCTSLIST_LOADING = 'SHOPPRODUCTSLIST_LOADING';
export const ADD_SHOPPRODUCTSLIST = 'ADD_SHOPPRODUCTSLIST';
export const SHOPPRODUCTSLIST_FAILED = 'SHOPPRODUCTSLIST_FAILED';


export const VENDORSHOPPRODUCTSLIST_LOADING = 'VENDORSHOPPRODUCTSLIST_LOADING';
export const ADD_VENDORSHOPPRODUCTSLIST = 'ADD_VENDORSHOPPRODUCTSLIST';
export const VENDORSHOPPRODUCTSLIST_FAILED = 'VENDORSHOPPRODUCTSLIST_FAILED';